### ISSUE TITLE
Heap and ETS

### ISSUE THREAD

**Issue by ghost** [aggelgian/erlang-algorithms#1]
The heap algorithm use ETS, but ETS will lose if the process crash unexpectedly.

**Comment by aggelgian** [comment]
Sorry for the late reply.
I am aware of this issue and I am planning to use heir processes in the concurrent version I am working on.

**Comment by csyangchen** [comment]
Also, a_star:run/4 need to delete the created heap, or we will encounter *\* Too many db tables *\* after many runs. Maybe heap NOT implemented in ets is preffered.
